pyrpl:
  background_color: ''
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\aj\0\0\x03\x90\xFC\
    \x01\0\0\0\x01\xFC\0\0\0\0\0\0\aj\0\0\0q\0\xFF\xFF\xFF\xFC\x02\0\0\0\x02\xFC\0\
    \0\0\x1A\0\0\x03\x90\0\0\0\xC3\0\xFF\xFF\xFF\xFC\x02\0\0\0\x02\xFC\0\0\0\x1A\0\
    \0\x01\xC6\0\0\0_\0\xFF\xFF\xFF\xFA\0\0\0\x03\x01\0\0\0\x04\xFB\0\0\0\"\0a\0s\0\
    g\0s\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\
    \0\xFF\xFF\xFF\xFB\0\0\0(\0l\0o\0c\0k\0b\0o\0x\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0\
    i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\xFF\xFF\xFF\xFB\0\0\0(\0l\0o\0c\0\
    k\0b\0o\0x\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\
    \0\0\0\0\0\0\0\xFB\0\0\0\"\0p\0i\0d\0s\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\x01\
    \0\0\0\0\0\0\a\x80\0\0\0q\0\xFF\xFF\xFF\xFB\0\0\0&\0s\0c\0o\0p\0e\0s\0 \0(\0R\0\
    P\01\0_\0c\0o\0n\0f\0i\0g\0)\x01\0\0\x01\xE5\0\0\x01\xC5\0\0\0_\0\xFF\xFF\xFF\xFC\
    \0\0\x02\xC0\0\0\0\xF2\0\0\0\0\0\xFF\xFF\xFF\xFA\xFF\xFF\xFF\xFF\x01\0\0\0\a\xFB\
    \0\0\0 \0i\0q\0s\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\
    \0\0\0\x1A\0\xFF\xFF\xFF\xFB\0\0\0$\0t\0r\0i\0g\0s\0 \0(\0R\0P\01\0_\0c\0o\0n\0\
    f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\xFF\xFF\xFF\xFB\0\0\0 \0h\0k\0\
    s\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\
    \xFF\xFF\xFF\xFB\0\0\08\0n\0e\0t\0w\0o\0r\0k\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0R\0\
    P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\xFF\xFF\xFF\
    \xFB\0\0\0:\0s\0p\0e\0c\0t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0R\0P\01\0_\0\
    c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\xFF\xFF\xFF\xFB\0\0\0\
    0\0c\0u\0r\0v\0e\0v\0i\0e\0w\0e\0r\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\
    \0\0\xFF\xFF\xFF\xFF\0\0\0\x1A\0\xFF\xFF\xFF\xFB\0\0\00\0p\0y\0r\0p\0l\0c\0o\0\
    n\0f\0i\0g\0 \0(\0R\0P\01\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\
    \0\x1A\0\xFF\xFF\xFF\0\0\aj\0\0\0\0\0\0\0\x04\0\0\0\x04\0\0\0\b\0\0\0\b\xFC\0\0\
    \0\0"
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: RP1_config
  window_position:
  - 0
  - 0
  - 1898
  - 963
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  gui: true
  hostname: 169.254.70.222
  leds_off: true
  monitor_server_name: pyrpl_server
  password: root
  port: 2222
  recompileserver: false
  reloadfpga: true
  reloadserver: true
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
scope:
  curve_name: scope curve
  running_state: running_continuous
  input1: in1
  duration: 0.000131072
  trigger_source: ext_positive_edge
  input2: pid0
  ch2_active: true
  ch1_active: true
  trace_average: 1
  hysteresis: 0.0
  trigger_delay: 6.0e-05
  threshold: 0.0999755859375
  xy_mode: false
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
lockbox:
  outputs:
    output1:
      assisted_design: true
      i: 100.0
      max_voltage: 0.2
      min_voltage: 0.0
      output_channel: out1
      p: 0.0
      sweep_amplitude: 0.12
      sweep_frequency: 1000.0
      sweep_offset: 0.12
      sweep_waveform: dc
      unit: V/V
    piezo:
      assisted_design: true
      i: 100.0
      max_voltage: 1.0
      min_voltage: -1.0
      output_channel: out2
      p: 0.0
      sweep_amplitude: 0.15
      sweep_offset: 0.15
      sweep_waveform: ramp
  sequence:
  - duration: 0.0
    function_call: ''
    gain_factor: 1.0
    input: input_from_output
    outputs:
      output1:
        lock_on: false
        offset: 0.0
        reset_offset: false
      piezo:
        lock_on: false
        offset: 0.0
        reset_offset: false
    setpoint: 10.0
  classname: Lockbox
  inputs:
    port1:
      calibration_data:
        max: 0.073486328125
        mean: 0.03214244544506073
        min: -0.009765625
        rms: 0.038271141173073626
      input_signal: pid0
    port2:
      calibration_data:
        max: 0.0731201171875
        mean: 0.03186844289302826
        min: -0.0101318359375
        rms: 0.03801397121348655
  final_stage:
    duration: 0.0
    function_call: ''
    gain_factor: 1.0
    input: port1
    outputs:
      output1:
        lock_on: false
        offset: 0.0
        reset_offset: false
      piezo:
        lock_on: false
        offset: 0.0
        reset_offset: false
    setpoint: 10.0
pid0:
  input: in1
  p: -0.10009765625
  pause_gains: pi
  output_direct: out1
  differential_mode_enabled: false
  min_voltage: 0.0
  max_voltage: 0.199951171875
  setpoint: 0.02001953125
  i: -9999.999848424037
  paused: true
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  paused_value: 0.199951171875
pid1:
  differential_mode_enabled: false
  i: 0.0
  input: in2
  inputfilter:
  - 0
  - 0
  - 0
  - 0
  max_voltage: 0.199951171875
  min_voltage: -0.199951171875
  output_direct: 'off'
  p: 0.0
  pause_gains: pi
  paused: true
  setpoint: 0.0
asg0:
  amplitude: 0.0
  offset: 0.0
  output_direct: 'off'
  trigger_source: 'off'
  waveform: dc
scope_states:
  autosweep:
    average: true
    ch1_active: true
    ch2_active: true
    ch_math_active: false
    curve_name: scope curve
    duration: 0.033554432
    hysteresis: 0.00244140625
    input1: in1
    input2: out1
    math_formula: ch1 * ch2
    rolling_mode: false
    running_state: stopped
    threshold: 0.0
    trace_average: 1
    trigger_delay: 0.0
    trigger_source: asg0
    xy_mode: false
pid2:
  differential_mode_enabled: false
  i: 0.0
  input: asg0
  max_voltage: 0.9998779296875
  min_voltage: -1.0
  output_direct: out2
  p: 0.0
  paused: false
  setpoint: 0.0
asg1:
  amplitude: 0.0
trig0:
  auto_rearm: true
  threshold: 0.0999755859375
  trigger_source: pos_edge
